"""create table packages

Revision ID: dda1bff0c5a2
Revises: 5525ccfe7f22
Create Date: 2023-11-30 07:59:00.142987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dda1bff0c5a2"
down_revision: Union[str, None] = "5525ccfe7f22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "packages",
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("passport", sa.String(), nullable=False),
        sa.Column("layer_number", sa.Integer(), nullable=False),
        sa.Column("mainland_hole", sa.String(), nullable=False),
        sa.Column("object_study_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["object_study_id"],
            ["objectstudys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("packages")
    # ### end Alembic commands ###
