"""create table partpots

Revision ID: 80acda186b69
Revises: 08fcd82162bb
Create Date: 2023-11-30 08:02:14.040680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80acda186b69"
down_revision: Union[str, None] = "08fcd82162bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "partpots",
        sa.Column("whisk", sa.Integer(), nullable=False),
        sa.Column("wall", sa.Integer(), nullable=False),
        sa.Column("bottom", sa.Integer(), nullable=False),
        sa.Column("package_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("partpots")
    # ### end Alembic commands ###
