# Generated by Django 4.2.7 on 2023-11-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_post_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Author',
        ),
    ]
